language: cpp

compiler: 
    - g++

addons:
    apt:
        packages:
            - bison
            - flex
            - llvm
            - clang

dist: trusty

script:
    - sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-3.4 33
    - make 
    - make debug
