language: cpp

compiler: 
    - g++

addons:
    apt:
        packages:
            - bison
            - flex
            - llvm
            - clang

dist: xenial
sudo: required

script:
    - make 
    - ./testcases.sh
