language: cpp

compiler: 
    - g++

addons:
    apt:
        packages:
            - bison
            - flex
            - llvm
            - clang
            - libedit-dev 

dist: trusty
sudo: required

script:
    - make 
    - ./testcases.sh
