language: cpp

compiler: 
    - g++

addons:
    apt:
        packages:
            - bison
            - flex
            - llvm
            - clang

sudo: required
dist: trusty

script:
    - make 

