language: cpp

compiler: 
    - g++

addons:
    apt:
        packages:
            - bison
            - flex
            - llvm
            - clang
	alternatives:
            - alternative:
                name: llvm-config
	        link: /usr/bin/llvm-config
	        path: /usr/bin/llvm-config-3.4
dist: trusty

sudo: required

script:
    - sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-3.4 33
    - make 
    - make debug
